# Generated by Django 3.2.18 on 2023-05-04 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0004_remove_additem_tax_additem_interstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_account', models.TextField(max_length=255)),
                ('amount', models.TextField(max_length=255)),
                ('expense_type', models.TextField(max_length=255)),
                ('paid', models.TextField(max_length=255)),
                ('vendor', models.TextField(max_length=255)),
                ('notes', models.TextField(max_length=255)),
                ('hsn_code', models.TextField(max_length=255)),
                ('gst_treatment', models.TextField(max_length=255)),
                ('destination_of_supply', models.TextField(max_length=255)),
                ('reverse_charge', models.TextField(max_length=255)),
                ('tax', models.TextField(max_length=255)),
                ('invoice', models.TextField(max_length=255)),
                ('customer_name', models.TextField(max_length=255)),
                ('reporting_tags', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
