# Generated by Django 3.2.18 on 2023-05-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='sac',
            field=models.TextField(default=100, max_length=255),
            preserve_default=False,
        ),
    ]
