# Generated by Django 3.2.18 on 2023-05-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_auto_20230509_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='pname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.account'),
        ),
    ]
