# Generated by Django 3.2.18 on 2023-05-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0011_expense_expense_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_account',
        ),
    ]
