# Generated by Django 3.2.18 on 2023-05-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_expense_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.TextField(default=100, max_length=255),
            preserve_default=False,
        ),
    ]
