# Generated by Django 3.2.18 on 2023-05-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_auto_20230516_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms', models.CharField(blank=True, max_length=100, null=True)),
                ('Days', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
