# Generated by Django 3.2.18 on 2023-05-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_payment_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcustomer',
            old_name='customerName',
            new_name='customer_name',
        ),
    ]
