# Generated by Django 3.2.18 on 2023-06-20 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0018_rename_customername_addcustomer_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('vendor_display_name', models.CharField(max_length=150)),
                ('vendor_email', models.CharField(max_length=250)),
                ('vendor_wphone', models.CharField(max_length=50)),
                ('vendor_mphone', models.CharField(max_length=50)),
                ('skype_number', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=250)),
                ('gst_treatment', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=50, null=True)),
                ('pan_number', models.CharField(max_length=50, null=True)),
                ('source_supply', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('opening_bal', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=100)),
                ('battention', models.CharField(default='', max_length=100)),
                ('bcountry', models.CharField(default='', max_length=100)),
                ('baddress', models.CharField(default='', max_length=300)),
                ('bcity', models.CharField(default='', max_length=100)),
                ('bstate', models.CharField(default='', max_length=100)),
                ('bzip', models.CharField(default='', max_length=100)),
                ('bphone', models.CharField(default='', max_length=100)),
                ('bfax', models.CharField(default='', max_length=100)),
                ('sattention', models.CharField(default='', max_length=100)),
                ('scountry', models.CharField(default='', max_length=100)),
                ('saddress', models.CharField(default='', max_length=300)),
                ('scity', models.CharField(default='', max_length=100)),
                ('sstate', models.CharField(default='', max_length=100)),
                ('szip', models.CharField(default='', max_length=100)),
                ('sphone', models.CharField(default='', max_length=100)),
                ('sfax', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='remarks_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_table')),
            ],
        ),
        migrations.CreateModel(
            name='contact_person_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('work_phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('skype_number', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_table')),
            ],
        ),
    ]
