# Generated by Django 3.2.18 on 2023-06-21 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_contact_person_table_remarks_table_vendor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_table'),
        ),
    ]
