# Generated by Django 4.2.2 on 2023-06-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0021_retag_alter_expense_reporting_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='reporting_tags',
            new_name='reporting_tag',
        ),
    ]
