# Generated by Django 4.2.2 on 2023-06-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0022_rename_reporting_tags_expense_reporting_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='reporting_tag',
        ),
        migrations.AddField(
            model_name='expense',
            name='reporting_tags',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='retag',
        ),
    ]
