# Generated by Django 4.2.2 on 2023-06-29 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0023_remove_expense_reporting_tag_expense_reporting_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='attachment',
        ),
        migrations.CreateModel(
            name='attach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment/')),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.expense')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
